require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OrbitsController do

  # This should return the minimal set of attributes required to create a valid
  # Orbit. As you add validations to Orbit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "planet_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # OrbitsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all orbits as @orbits" do
      orbit = Orbit.create! valid_attributes
      get :index, {}, valid_session
      assigns(:orbits).should eq([orbit])
    end
  end

  describe "GET show" do
    it "assigns the requested orbit as @orbit" do
      orbit = Orbit.create! valid_attributes
      get :show, {:id => orbit.to_param}, valid_session
      assigns(:orbit).should eq(orbit)
    end
  end

  describe "GET new" do
    it "assigns a new orbit as @orbit" do
      get :new, {}, valid_session
      assigns(:orbit).should be_a_new(Orbit)
    end
  end

  describe "GET edit" do
    it "assigns the requested orbit as @orbit" do
      orbit = Orbit.create! valid_attributes
      get :edit, {:id => orbit.to_param}, valid_session
      assigns(:orbit).should eq(orbit)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Orbit" do
        expect {
          post :create, {:orbit => valid_attributes}, valid_session
        }.to change(Orbit, :count).by(1)
      end

      it "assigns a newly created orbit as @orbit" do
        post :create, {:orbit => valid_attributes}, valid_session
        assigns(:orbit).should be_a(Orbit)
        assigns(:orbit).should be_persisted
      end

      it "redirects to the created orbit" do
        post :create, {:orbit => valid_attributes}, valid_session
        response.should redirect_to(Orbit.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved orbit as @orbit" do
        # Trigger the behavior that occurs when invalid params are submitted
        Orbit.any_instance.stub(:save).and_return(false)
        post :create, {:orbit => { "planet_id" => "invalid value" }}, valid_session
        assigns(:orbit).should be_a_new(Orbit)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Orbit.any_instance.stub(:save).and_return(false)
        post :create, {:orbit => { "planet_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested orbit" do
        orbit = Orbit.create! valid_attributes
        # Assuming there are no other orbits in the database, this
        # specifies that the Orbit created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Orbit.any_instance.should_receive(:update_attributes).with({ "planet_id" => "1" })
        put :update, {:id => orbit.to_param, :orbit => { "planet_id" => "1" }}, valid_session
      end

      it "assigns the requested orbit as @orbit" do
        orbit = Orbit.create! valid_attributes
        put :update, {:id => orbit.to_param, :orbit => valid_attributes}, valid_session
        assigns(:orbit).should eq(orbit)
      end

      it "redirects to the orbit" do
        orbit = Orbit.create! valid_attributes
        put :update, {:id => orbit.to_param, :orbit => valid_attributes}, valid_session
        response.should redirect_to(orbit)
      end
    end

    describe "with invalid params" do
      it "assigns the orbit as @orbit" do
        orbit = Orbit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Orbit.any_instance.stub(:save).and_return(false)
        put :update, {:id => orbit.to_param, :orbit => { "planet_id" => "invalid value" }}, valid_session
        assigns(:orbit).should eq(orbit)
      end

      it "re-renders the 'edit' template" do
        orbit = Orbit.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Orbit.any_instance.stub(:save).and_return(false)
        put :update, {:id => orbit.to_param, :orbit => { "planet_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested orbit" do
      orbit = Orbit.create! valid_attributes
      expect {
        delete :destroy, {:id => orbit.to_param}, valid_session
      }.to change(Orbit, :count).by(-1)
    end

    it "redirects to the orbits list" do
      orbit = Orbit.create! valid_attributes
      delete :destroy, {:id => orbit.to_param}, valid_session
      response.should redirect_to(orbits_url)
    end
  end

end
